# Generated by Django 4.2.2 on 2023-06-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content_type',
            field=models.CharField(choices=[('TXT', 'Text'), ('VID', 'Video'), ('AUD', 'Audio'), ('IMG', 'Image'), ('GIF', 'Gif')], default='TXT', max_length=3),
        ),
    ]
