# Generated by Django 4.2.2 on 2023-06-06 12:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_botadmins_alter_message_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='day',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='Sending day'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='sent_at',
            field=models.DateTimeField(verbose_name='Sending date & time'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='Telegram ID'),
        ),
    ]
