# Generated by Django 4.2.2 on 2023-06-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_botadmins_first_name_alter_botadmins_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botadmins',
            name='reg_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(auto_now=True, help_text='Дата первой активации бота', verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.message'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='sent_at',
            field=models.DateTimeField(editable=False, help_text='Дата, когда было отправлено сообщение', verbose_name='Sending date & time'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='Telegram ID'),
        ),
    ]
