# Generated by Django 4.2.2 on 2023-06-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_user_reg_date_alter_usermessage_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botadmins',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID'),
        ),
    ]
