# Generated by Django 4.2.2 on 2023-06-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_botadmins_user_id_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Дата прохождения квиза', verbose_name='Quiz date')),
                ('result', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user', verbose_name='Telegram ID')),
            ],
        ),
    ]
