# Generated by Django 4.2.2 on 2023-06-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_quizquestions_quizresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresults',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='Telegram ID'),
        ),
    ]
