# Generated by Django 4.2.2 on 2023-06-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_quizresults_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('ARTICLE', '📖 Статья'), ('MEDITATION', '🧘\u200d♀️ Медитация'), ('WORKOUT', '🏋️\u200d♀️ Упражнение')], default='ARTICLE', max_length=10),
        ),
    ]
