# Generated by Django 4.2.2 on 2023-06-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.BigIntegerField(default=None, unique=True, verbose_name='Tg Chat ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Tg User ID'),
        ),
    ]
