# Generated by Django 4.2.2 on 2023-06-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_user_chat_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marathon_completed',
            field=models.BooleanField(default=False, help_text='Статус завершения марафона'),
        ),
    ]
