# Generated by Django 4.2.2 on 2023-06-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='short_name',
            field=models.CharField(default=None, help_text='Короткое название, не более 15 символов, появится справа от кнопки', max_length=15),
        ),
    ]
