# Generated by Django 4.2.2 on 2023-06-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_message_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_name',
            field=models.CharField(default=None, help_text='Короткое название (40 символов), появится справа от emoji', max_length=40),
        ),
    ]
