# Generated by Django 4.2.2 on 2023-06-06 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_alter_user_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botadmins',
            name='first_name',
            field=models.CharField(blank=True, help_text='Имя пользователя', max_length=30),
        ),
        migrations.AlterField(
            model_name='botadmins',
            name='last_name',
            field=models.CharField(blank=True, help_text='Фамилия пользователя', max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='day',
            field=models.IntegerField(help_text='Номер дня по счету от даты регистрации, когда отправить сообщение', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='Sending day'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(help_text='Дата первой активации бота', verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(help_text='Часовой пояс пользователя', max_length=10),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='sent_at',
            field=models.DateTimeField(help_text='Дата, когда было отправлено сообщение', verbose_name='Sending date & time'),
        ),
    ]
