# Generated by Django 4.2.2 on 2023-06-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0008_alter_user_user_id_alter_usermessage_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botadmins',
            name='user_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID'),
        ),
    ]
