# Generated by Django 4.2.2 on 2023-06-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0011_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ordinal_number',
            field=models.IntegerField(help_text='Порядковый номер отправки (уникальный)', unique=False),
        ),
    ]
